project:
  type: website
  render:
  - "*.qmd"
  - "!utils/"
  post-render:
  - "cp -r img _site/"
  - "cp -r docs _site/pkgdown"
  - "cp -r utils/screenshots _site/screenshots"

website:
  title: "Supported By Posit Badge"
  favicon: img/posit-logo.png
  navbar:
    left:
      - text: "Quarto demo"
        href: index.qmd
      - text: "pkgdown demo"
        href: pkgdown/index.html
    right:
      - icon: github
        href: https://github.com/posit-dev/supported-by-posit

format:
  html:
    include-in-header:
      - text: |
          <script src="js/badge.js"></script>
          <script defer data-domain="https://posit-dev.github.io/supported-by-posit/" src="https://plausible.io/js/plausible.js">

    theme:
      light: yeti
      dark: superhero
    toc: true
    page-layout: full

